# Generated by Django 3.1 on 2020-08-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='signup',
        ),
    ]
