# Generated by Django 3.1 on 2020-08-26 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200825_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='msg_id',
            new_name='user_id',
        ),
    ]
