# Generated by Django 3.1 on 2020-08-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200826_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='username',
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(default='', max_length=70),
        ),
    ]
